name = "roadster"
license = "GPLv2"
licenselink = "https://github.com/mansoorbarri/roadster/blob/master/LICENSE.md"
description = "roadster is a responsive, clean and content-focused Hugo theme."
homepage = "https://github.com/mansoorbarri/roadster/"
demosite = "https://roadster-hugo.pages.dev/"
tags = ["blog", "responsive", "light", "multilingual", "customizable", "widgets", "wordpress"]
features = ["blog", "responsive", "multilingual", "widgets", "rss", "disqus", "google analytics", "wordpress"]
min_version = "0.128.0"

[author]
  name = "Mansoor Barri"
  homepage = "https://mansoorbarri.com/"

# If porting an existing theme
[original]
  name = "Mainroad"
  homepage = "https://mainroad-demo.netlify.app/"
  repo = "https://github.com/Vimux/Mainroad"
